/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#afb3ac',
        'on-secondary-fixed': '#2e4153',
        surface: '#fafaf5',
        'on-tertiary': '#fff7f3',
        'primary-dim': '#40584b',
        'primary-fixed': '#cde9d8',
        'tertiary-fixed-dim': '#eed9c6',
        'surface-container-low': '#f3f4ee',
        'surface-container-highest': '#e0e4dc',
        'secondary-container': '#d1e4fc',
        'on-primary-fixed-variant': '#486153',
        'tertiary-container': '#fde7d3',
        'tertiary-fixed': '#fde7d3',
        'on-error': '#fff7f6',
        'primary-fixed-dim': '#bfdbca',
        'error-dim': '#67040d',
        'inverse-surface': '#0d0f0c',
        'on-tertiary-fixed-variant': '#6d5e4f',
        'on-secondary-container': '#415366',
        'on-surface-variant': '#5c605a',
        'inverse-primary': '#d8f5e3',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#635445',
        'on-primary-container': '#3e574a',
        'inverse-on-surface': '#9c9d99',
        'tertiary-dim': '#5f5142',
        'surface-container-high': '#e7e9e2',
        'error-container': '#fa746f',
        'surface-variant': '#e0e4dc',
        'on-background': '#2f342e',
        tertiary: '#6c5c4d',
        'on-primary': '#e6ffef',
        secondary: '#4e6174',
        'on-primary-fixed': '#2c4438',
        'secondary-fixed-dim': '#c3d6ed',
        'on-tertiary-fixed': '#504234',
        error: '#a83836',
        outline: '#787c75',
        background: '#fafaf5',
        'on-surface': '#2f342e',
        'surface-bright': '#fafaf5',
        'on-secondary': '#f6f9ff',
        'on-error-container': '#6e0a12',
        primary: '#4c6557',
        'secondary-fixed': '#d1e4fc',
        'surface-container': '#edefe8',
        'secondary-dim': '#425568',
        'surface-dim': '#d8dbd3',
        'primary-container': '#cde9d8',
        'surface-tint': '#4c6557',
        'on-secondary-fixed-variant': '#4b5d71',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
