import { useEffect, useRef } from 'react'
import { Navbar } from '@/components/layout/Navbar'
import { Sidebar } from '@/components/layout/Sidebar'
import { BottomNav } from '@/components/layout/BottomNav'
import { Icon } from '@/components/shared/Icon'
import { useChat } from '@/hooks/useChat'
import { downloadConversation } from '@/lib/exportConversation'

export function Legal() {
  const { messages, input, setInput, send, isLoading, error } = useChat('legal')
  const scrollRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' })
  }, [messages, isLoading])

  function handleKeyDown(e: React.KeyboardEvent<HTMLInputElement>) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      send()
    }
  }

  return (
    <div className="text-on-background selection:bg-primary-container selection:text-on-primary-container">
      <Navbar quickExitIcon />
      <div className="flex h-screen overflow-hidden pt-16">
        <Sidebar helpVariant="advocate" />
        <main className="flex-1 lg:ml-64 flex flex-col relative h-full bg-background">
          <div className="absolute top-0 right-0 w-1/3 h-1/3 bg-primary-container/20 blur-[120px] rounded-full pointer-events-none -z-10" />
          <div className="absolute bottom-10 left-10 w-1/4 h-1/4 bg-tertiary-container/20 blur-[100px] rounded-full pointer-events-none -z-10" />

          {/* Chat Header */}
          <div className="px-8 pt-8 pb-4 flex flex-col gap-2">
            <div className="flex items-center gap-2 text-primary font-bold tracking-tight">
              <Icon name="gavel" />
              <span className="uppercase text-xs tracking-[0.2em]">Legal Module</span>
            </div>
            <h2 className="text-3xl md:text-4xl font-headline font-bold text-on-background leading-tight">
              Compass Guidance
            </h2>
            <p className="text-on-surface-variant max-w-2xl text-lg">
              Navigating legal rights can feel overwhelming. I'm here to provide clear steps and
              resources based on your situation.
            </p>
          </div>

          {/* Chat Container */}
          <div ref={scrollRef} role="log" aria-live="polite" aria-label="Conversation" data-lenis-prevent className="flex-1 overflow-y-auto px-8 py-6 space-y-8 hide-scrollbar">
            {/* Disclaimer Box */}
            <div className="bg-surface-container-low p-5 rounded-2xl border-l-4 border-primary/30 max-w-3xl">
              <div className="flex gap-3">
                <Icon name="info" className="text-primary text-xl" />
                <div className="text-sm text-on-surface-variant leading-relaxed">
                  <span className="font-bold text-on-surface block mb-1">
                    Important Legal Disclaimer
                  </span>
                  This guidance is generated by AI to help you understand general rights and
                  potential next steps. It is <span className="font-semibold text-primary">not legal advice</span> and
                  does not create an attorney-client relationship. Please consult with a licensed
                  professional for legal representation.
                </div>
              </div>
            </div>

            {messages.length === 0 && (
              <div className="flex justify-center">
                <div className="bg-surface-container-highest px-4 py-2 rounded-full text-xs font-semibold text-on-surface-variant uppercase tracking-widest">
                  Ask about rights, protective orders, or local resources
                </div>
              </div>
            )}

            {messages.map((message, index) => {
              const isUser = message.role === 'user'
              if (isUser) {
                return (
                  <div key={`${message.timestamp}-${index}`} className="flex gap-4 max-w-4xl ml-auto flex-row-reverse">
                    <div className="w-10 h-10 rounded-full bg-secondary-fixed flex items-center justify-center shrink-0">
                      <Icon name="person" className="text-on-secondary-fixed" />
                    </div>
                    <div className="space-y-2">
                      <div className="bg-primary text-on-primary p-5 rounded-2xl rounded-tr-none shadow-md shadow-primary/10 text-sm leading-relaxed">
                        {message.content}
                      </div>
                      <div className="text-[10px] text-on-surface-variant opacity-50 text-right mr-2">
                        Sent
                      </div>
                    </div>
                  </div>
                )
              }
              return (
                <div key={`${message.timestamp}-${index}`} className="flex gap-4 max-w-4xl">
                  <div className="w-10 h-10 rounded-full bg-primary-container flex items-center justify-center shrink-0">
                    <Icon name="explore" className="text-primary" />
                  </div>
                  <div className="space-y-4">
                    <div className="bg-surface-container-lowest p-6 rounded-2xl rounded-tl-none shadow-sm border border-outline-variant/10 text-on-surface leading-relaxed">
                      {message.content}
                    </div>
                    <div className="text-[10px] text-on-surface-variant opacity-50 ml-2">
                      Compass
                    </div>
                  </div>
                </div>
              )
            })}

            {isLoading && (
              <div className="flex gap-4 max-w-4xl">
                <div className="w-10 h-10 rounded-full bg-primary-container flex items-center justify-center shrink-0">
                  <Icon name="explore" className="text-primary" />
                </div>
                <div className="bg-surface-container-lowest px-6 py-4 rounded-2xl rounded-tl-none shadow-sm flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-primary/30 animate-pulse" />
                  <span className="w-2 h-2 rounded-full bg-primary/30 animate-pulse delay-75" />
                  <span className="w-2 h-2 rounded-full bg-primary/30 animate-pulse delay-150" />
                  <span className="text-xs text-on-surface-variant italic ml-2">Thinking…</span>
                </div>
              </div>
            )}
          </div>

          {error && (
            <p role="alert" className="px-8 text-xs font-medium text-error">
              {error}
            </p>
          )}

          {/* Input Area — extra bottom padding clears the mobile BottomNav. */}
          <div className="px-4 pb-24 pt-4 md:p-8 md:pt-4">
            <div className="max-w-4xl mx-auto glass-panel p-2 pl-6 rounded-full shadow-lg flex items-center gap-2 border border-surface-container-highest">
              <label htmlFor="legal-input" className="sr-only">
                Message
              </label>
              <input
                id="legal-input"
                className="flex-1 bg-transparent border-none focus:ring-0 text-on-surface placeholder:text-outline-variant font-medium px-4"
                placeholder="Ask Compass about your rights or legal steps..."
                type="text"
                autoComplete="off"
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={handleKeyDown}
              />
              <button
                type="button"
                onClick={send}
                disabled={isLoading || !input.trim()}
                aria-label="Send message"
                className="bg-primary text-on-primary w-12 h-12 rounded-full flex items-center justify-center shadow-md hover:scale-105 active:scale-95 transition-all disabled:opacity-40"
              >
                <Icon name="send" />
              </button>
            </div>
            <div className="mt-4 flex flex-wrap justify-center gap-6">
              <button
                type="button"
                onClick={() => downloadConversation('legal', messages)}
                disabled={messages.length === 0}
                className="text-[10px] font-bold uppercase tracking-widest text-on-surface-variant hover:text-primary transition-colors flex items-center gap-1 disabled:opacity-40 disabled:hover:text-on-surface-variant"
              >
                <Icon name="download" className="text-sm" />
                Export Conversation
              </button>
              <button
                type="button"
                onClick={() => window.print()}
                disabled={messages.length === 0}
                className="text-[10px] font-bold uppercase tracking-widest text-on-surface-variant hover:text-primary transition-colors flex items-center gap-1 disabled:opacity-40 disabled:hover:text-on-surface-variant"
              >
                <Icon name="print" className="text-sm" />
                Print
              </button>
            </div>
          </div>
        </main>
      </div>
      <BottomNav />
    </div>
  )
}
